becheran/grid

Cargo.toml
src/lib.rs

This does not change behavior for those who don't need no_std compatibility. 
If you declare the Grid-dependency like this after merge: 
```toml
grid = { version = "0.4.0", default-features = false }
```
You can use it on embedded devices assuming you have a memory allocator.
Both `cargo test --no-default-features` and `cargo test` still pass all tests.

made Grid no_std compatible + removed stray logging

---

src/lib.rs

The `T: Clone` on the whole main `impl` is overly restrictive, only a
few operations really need to clone grid elements.

Remove several unnecessary "Clone" bounds

---

src/lib.rs

Improve development experience by extending `alternate()` formatting options to the `grid` struct.
This includes:
1. new line formatting
2. width parameter
3. precision parameter
Tests included.
Using the `alternate()` flag in a predictable way helps achieve 👇
> Most of the functions std::Vec<T> offer are also implemented in grid and slightly modified for a 2D data object.
In my testing I found that `str` and `String` don't respect the width/padding features of `format!()`. 
This results in most grids of strings (or compound types containing them) being doomed to look uneven.
If anyone knows how to address that I'd love to learn 😄

Alternate Debug Formatting

---

src/lib.rs

I believe flipping the size references fixes the issue. If not please let me know 😄 
```
use grid::*;
fn main() {
let mut grid = grid![
[1,2,3]
[4,5,6]
];
// thread 'main' panicked at 'Out of range. Index was 3, but must be less or equal to 3.'
//                                                                                    ^ should say 2
grid.insert_row(3, vec![7,8,9]);
// thread 'main' panicked at 'Out of range. Index was 4, but must be less or equal to 2.'
//                                                                                    ^ should say 3
grid.insert_col(4, vec![11, 11])
}
```

flip cols/rows in `out of range` panic

---

.github/workflows/rust.yml
Cargo.toml
src/lib.rs

It's easy to just import the types from the `core` and `alloc` libraries directly. No need for the dependency.
This PR:
- Make that changes and removes the `no_std_compat` dependency
- Adds configuration to run tests with the no_std (well, alloc) config in CI

Remove "no-std-compat" dependency

---

src/lib.rs

I achieved this by creating a `GridIndexedIter` which returns references to each element in the vector. The row and column are calculated from the 'linear' index.
I did try to write a meaningful test as well as documentation.
I hope this closes #11.

Add `indexed_iter` to allow traversing with row/col indexes

---

benches/benches.rs
src/lib.rs

Hi,
Since the grid library has been useful for a personnal project, I wanted to contribute and tried to tackle #16.
I wondered if I should add unit tests but I think the doc-tests are enough, right ?
I also took the liberty of implementing 180° rotation, to have full rotation capabilities.
I hope this helps!

Implement rotation methods

---

benches/benches.rs
src/lib.rs

Hi, I started working on my proposition from #33.
It is far from finished, but I wanted to open the PR as soon as possible, in case you have time to take a look and had early remarks to make.

Add support for column-major grid order

---

src/lib.rs

I think this should work to make this hashable if the element type is hashable. Closes #43.

fix: make Grid hashable if T is hashable

---

Cargo.toml
src/lib.rs

While using this library, I found it difficult to get neighbors because of the possibility of overflows when going negative. For instance, to get the neighbor that is up and to the left of the current cell, I would have to something like this:
```rust
let row: usize = 0;
let col: usize = 0;
if let Some(row) = row.checked_sub(1) {
if let Some(col) = col.checked_sub(1) {
if let Some(cell) = grid.get(row, col) {
dbg!(cell);
}
}
}
```
This was a lot of code. Ideally, I could just do this:
```rust
let row: isize = 0;
let col: isize = 0;
if let Some(cell) = grid.get(row - 1, col - 1) {
dbg!(cell);
}
```
Unfortunately, `.get` and `.get_mut` do not accept anything but `usize`, so this would cause an overflow warning.
I started adding this to my rust projects:
```rust
trait GetChecked<T> {
fn …
```

Improve `get` and `get_mut` method signature, Add From implementations for Vec<Vec<T>> and (Vec<T>, usize)

---

Cargo.toml
src/lib.rs

feat: ✨ Add a new method called indexed_iter_mut

Add more mutable iterator methods

---

src/lib.rs

I wrote implementations of ExactSizeIterator and DoubleEndedIterator for GridRowIter and GridColIter.
- adds one usize of additional memory usage to both types
- makes both more versatile and maybe even faster (e.g. when collecting into a vec ExactSizeIterator should reduce the needed allocations)
The changes to Iterator are bigger than actually needed, but now the next and next_back functions look very similar.
Iterator still passes all test. I also added tests for all new code.
Maybe closes https://github.com/becheran/grid/issues/38, which i just notices while writing this.

Add ExactSize and DoubleEnded impls to GridRow and Col Iter

---

src/lib.rs

closes https://github.com/becheran/grid/issues/42

implemended swap

---

src/lib.rs

Closes https://github.com/becheran/grid/issues/27.
Not really happy with with_capacity_panics_vec test as there are multiple panic reasons possible, while i only want to check one, but i don't know enough about rust testing to do it better.

implemented with_capacity

---

Cargo.toml

This value was based on the use of `fill_with` (Rust tells you this if you try to set it).

chore: add min version of Rust

---

src/lib.rs

Some things clippy warns about in 1.83.
The second commit adds the nursery checks too, which seemed useful, but I could drop it if preferred.

chore: address some clippy lints

---

src/lib.rs

This adds a way to apply a function (possibly changing the type) and produce a new Grid. For example, given a grid, you could produce a mask by applying a function producing a boolean (examples in docs).

feat: add a map and map_ref method

---

src/lib.rs

This removes a clippy lint, which states anything with `.iter()` should implement `IntoIter` (and likewise for `mut` versions).
Fix #49.

fix: add missing IntoIter

---

src/lib.rs

Hi, I added methods to allow the grid to be expanded by x rows or x cols without the need do a lot of push_rows or push_cols. I don't know if it is a problem, but as I needed to initialize some data to those new rows or cols, i implemented this only for type T that haves the trait Default.
I believe that the benefits of this methods are to make it easier to someone using the lib to expand the grid and also to allow the grid to be expanded with less reallocations of it internal data Vec.
This is my very first contribution to an open source project so if there anything that should be improved, please, feel free to say.

feat: add expand_rows and expand_cols

---

benches/benches.rs
src/lib.rs

Building on #64, I added functionality to expand grids in the other direction.
Should probably rename either these or the expand_* functions as they don't match now.
I like prepend / append as they convey directionality, but they also kind of imply insertion of data rather than just resizing.
Alternatively something like expand_rows_before could work.
Thoughts?

feat: add prepend_rows and prepend_cols
